name: Sync to GitLab

on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3 # Updated to v3

    - name: Push to GitLab
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
      run: |
        git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/duynguyenvt97/docs.git
        git push --mirror gitlab
